name: lerna publish
on:
  pull_request:
    branches:
      - master
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true 
      - name: Install
        run: |
          npm install
      - name: Test
        run: lerna run test
      - name: Publish
        run: lerna changed