name: lerna publish
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: "0"
      - run: git fetch --depth=1 origin +refs/tags/*:refs/tags/*
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          check-latest: true 
      - name: Install and Test
        run: |
          npm ci
          npm run test
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Changed
        run: lerna changed
      - name: Publish
        run: npm run lerna:publish
        env: 
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
